### ISSUE TITLE
add Keen.io integration

### ISSUE THREAD

**Issue by jipiboily** [jipiboily/forwardlytics#11]

**Comment by helgeblod** [comment]
I can have a look at this one if you want

**Comment by jipiboily** [comment]
I'm not really using Keen at the moment...not sure it would be a good idea to build this without having someone to dog food this. If you know Keen enough to know what and how to build this, then maybe. Really your call, but less likely to be useful on the short term.

**Comment by helgeblod** [comment]
I've never used keen.io for anything so then I suggest we wait until we have a use case.

**Comment by jipiboily** [comment]
Let's close for now. We'll re-open where there is a legit use case.
