### ISSUE TITLE
Waffle badge broken?

### ISSUE THREAD

**Issue by jipiboily** [jipiboily/forwardlytics#24]
It shows zero stories in progress, but there is one!

Any idea @GabLeRoux

**Comment by GabLeRoux** [comment]
Yeah you're right, I kind of hardcoded this by having a look at an other readme from a different project, not sure if we need to do something special, but it should be 1 right now according to waffle board.

**Comment by jipiboily** [comment]
Lookign...

**Comment by GabLeRoux** [comment]
Ah that's probably the `?label=waffle%3Ain%20progress` I got wrong. case sensitive maybe?

**Comment by jipiboily** [comment]
Ok, URL should be `https://badge.waffle.io/jipiboily/forwardlytics.svg?label=In%20Progress&title=In%20Progress`, fixing.
