### ISSUE TITLE
Intercom integration raises an error when user does not exists yet

### ISSUE THREAD

**Issue by jipiboily** [jipiboily/forwardlytics#48]
Here's an example: https://www.dropbox.com/s/ft62lvsikff7ktf/Screenshot%202017-02-15%2007.22.03.png?dl=0

I am wondering if it's raising this error before retrying? Because it looks like it ends up working and creating it on Intercom.

Any idea?

**Comment by helgeblod** [comment]
I'll have a look in a few days :)

**Comment by jipiboily** [comment]
Awesome, thanks! ❤️

**Comment by helgeblod** [comment]
Is it possible to assign this to me so it shows up as an assigned issue in my end?

**Comment by jipiboily** [comment]
@helgeblod apparently not...at least not if you're not a collaborator on the repo it looks like. Just invited you. Let me know when you accepted it, I'll assign you then (or maybe you can assign yourself?).

**Comment by helgeblod** [comment]
Cool, assigned myself now 👍

**Comment by helgeblod** [comment]
The reason for this error is pretty straightforward: the Intercom api will return a 404 not found when submitting events with a user id that is unknown to intercom (ie the user has not been created before the event is submitted). 

IMHO we should either return a `400` from the `/track` endpoint or we should auto-create the user before sending the event. If a valid use of forwardlytics is to call `/track` with a userID that hasn't been created first using `/identify`, then I suggest auto-create, if not, `400` Bad Request. 

Any thoughts @jipiboily?

**Comment by jipiboily** [comment]
I would go for auto-create. The only possible downside I see is that it could be created in some case by us and the widget at the same time, and result in two different users on Intercom. Willing to take the risk.

Thanks!

**Comment by jipiboily** [comment]
Fixed by #49.
