### ISSUE TITLE
make it robust enough to use in small apps, that are not too critical to start with

### ISSUE THREAD

**Issue by jipiboily** [jipiboily/forwardlytics#9]

**Comment by jipiboily** [comment]
Things are going well. If all goes well, it should be usable now...but let's give it another week.

**Comment by helgeblod** [comment]
So what's the task here? Any areas of the app that aren't stable enough and that needs work that you know about? Doing some work based on the current description is a bit hard 😃

**Comment by jipiboily** [comment]
Not much. There is an issue when I try to send a "Signed Up" event as the user is not yet created, I think. You don't have to do anything here, it's super broad. I will actually close it :)
